version: '3'
services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app_name
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: output-is-fun-service
        awslogs-region: ap-northeast-1 
        awslogs-stream-prefix: output-is-fun
